function p = pathdef(path2ugm)

p = [...
		 pwd, ...
     ':',path2ugm,'/UGM', ...
     ':',path2ugm,'/UGM/compiled', ...
     ':',path2ugm,'/UGM/decode', ...
     ':',path2ugm,'/UGM/examples', ...
     ':',path2ugm,'/UGM/infer', ...
     ':',path2ugm,'/UGM/mex', ...
     ':',path2ugm,'/UGM/misc', ...
     ':',path2ugm,'/UGM/sample', ...
     ':',path2ugm,'/UGM/struct', ...
     ':',path2ugm,'/UGM/train', ...
     ':',path2ugm,'/minFunc', ...
     ':',path2ugm,'/minFunc/autoDiff', ...
     ':',path2ugm,'/minFunc/compiled', ...
     ':',path2ugm,'/misc', ...
     ':',path2ugm,'/misc/compiled', ...
];
