function p = pathdef(path2mark)

p = [...
		 pwd, ...
     ':',path2mark,'/UGM', ...
     ':',path2mark,'/UGM/compiled', ...
     ':',path2mark,'/UGM/decode', ...
     ':',path2mark,'/UGM/examples', ...
     ':',path2mark,'/UGM/infer', ...
     ':',path2mark,'/UGM/mex', ...
     ':',path2mark,'/UGM/misc', ...
     ':',path2mark,'/UGM/sample', ...
     ':',path2mark,'/UGM/struct', ...
     ':',path2mark,'/UGM/train', ...
     ':',path2mark,'/minFunc', ...
     ':',path2mark,'/minFunc/autoDiff', ...
     ':',path2mark,'/minFunc/compiled', ...
     ':',path2mark,'/misc', ...
     ':',path2mark,'/misc/compiled', ...
];
